name: Upload Release Asset

on:
  release:
    types:
      - created
      - edited
      - prereleased

jobs:
  spawn-datapack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package Datapack!
        run: zip -r soultaker-datapack.zip data pack.mcmeta
      - name: Package Resourcepack!
        run: zip -r soultaker-resource.zip resources
      - name: Upload them!
        id: upload-release-asset
        uses: actions/upload-release-assert@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          assert_path: |
            soultaker-datapack.zip
            soultaker-resource.zip
          assert_content_type: application/zip
