name: Upload Dev Asset

on:
  push:
    tags:
      - 'dev*'

jobs:
  spawn-datapack:
    name: Build!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package Datapack!
        run: ls -al && zip -r soultaker-datapack-$GITHUB_REF_NAME.zip data pack.mcmeta LICENSE
      - name: Package Resourcepack!
        run: cd ./resources && zip -r ../soultaker-resource-$GITHUB_REF_NAME.zip ./* ../LICENSE && cd ..
      - name: Package all!
        run: ls -al && zip soultaker-datapack-with-resources-$GITHUB_REF_NAME.zip *.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} 测试包发布！
          draft: true
          prerelease: false
      - name: Position
        run: ls -al
      - name: Upload them!
        id: upload-release-asset
        uses: sekwah41/upload-release-assets@v1.1.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.zip
          asset_name: soultaker-datapack-with-resources-$GITHUB_REF_NAME.zip
          asset_content_type: application/zip
